/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type WorkItem = {
	_id: string;
	_type: "workItem";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	company?: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: "company";
	};
	title?: string;
	icon?: CloudinaryAsset;
	tag?: string;
	image?: CloudinaryAsset;
	description?: string;
	slug?: Slug;
	order?: number;
};

export type Slug = {
	_type: "slug";
	current?: string;
	source?: string;
};

export type CloudinaryAsset = {
	_type: "cloudinary.asset";
	public_id?: string;
	resource_type?: string;
	type?: string;
	format?: string;
	version?: number;
	url?: string;
	secure_url?: string;
	width?: number;
	height?: number;
	bytes?: number;
	duration?: number;
	tags?: Array<string>;
	created_at?: string;
	derived?: Array<
		{
			_key: string;
		} & CloudinaryAssetDerived
	>;
	access_mode?: string;
	context?: CloudinaryAssetContext;
};

export type Testimonial = {
	_id: string;
	_type: "testimonial";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	quote?: string;
	authorName?: string;
	authorRole?: string;
	company?: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: "company";
	};
	authorAvatar?: CloudinaryAsset;
	order?: number;
};

export type Social = {
	_id: string;
	_type: "social";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	label?: string;
	href?: string;
	icon?: CloudinaryAsset;
	order?: number;
};

export type SiteProfile = {
	_id: string;
	_type: "siteProfile";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	title?: string;
	bio?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: "span";
			_key: string;
		}>;
		style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
		listItem?: "bullet" | "number";
		markDefs?: Array<{
			href?: string;
			_type: "link";
			_key: string;
		}>;
		level?: number;
		_type: "block";
		_key: string;
	}>;
};

export type SectionHeader = {
	_id: string;
	_type: "sectionHeader";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title?: string;
	headingPrefix?: string;
	headingHighlight?: string;
	headingEmoji?: string;
	icon?: CloudinaryAsset;
	gradientFrom?: string;
	gradientTo?: string;
	video?: CloudinaryAsset;
	subheading?: string;
};

export type Project = {
	_id: string;
	_type: "project";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	image?: CloudinaryAsset;
	alt?: string;
	backgroundColor?: string;
	order?: number;
};

export type Experience = {
	_id: string;
	_type: "experience";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	company?: string;
	url?: string;
	role?: string;
	description?: string;
	order?: number;
};

export type Company = {
	_id: string;
	_type: "company";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	logo?: CloudinaryAsset;
	website?: string;
	description?: string;
	isCurrent?: boolean;
	workTagline?: string;
	workDescription?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: "span";
			_key: string;
		}>;
		style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
		listItem?: "bullet" | "number";
		markDefs?: Array<{
			href?: string;
			_type: "link";
			_key: string;
		}>;
		level?: number;
		_type: "block";
		_key: string;
	}>;
	order?: number;
};

export type CloudinaryAssetContextCustom = {
	_type: "cloudinary.assetContextCustom";
	alt?: string;
	caption?: string;
};

export type CloudinaryAssetContext = {
	_type: "cloudinary.assetContext";
	custom?: CloudinaryAssetContextCustom;
};

export type CloudinaryAssetDerived = {
	_type: "cloudinary.assetDerived";
	raw_transformation?: string;
	url?: string;
	secure_url?: string;
};

export type SanityImagePaletteSwatch = {
	_type: "sanity.imagePaletteSwatch";
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: "sanity.imagePalette";
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: "sanity.imageDimensions";
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageMetadata = {
	_type: "sanity.imageMetadata";
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityImageHotspot = {
	_type: "sanity.imageHotspot";
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type SanityImageCrop = {
	_type: "sanity.imageCrop";
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityFileAsset = {
	_id: string;
	_type: "sanity.fileAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: "sanity.assetSourceData";
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: "sanity.imageAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: "geopoint";
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| WorkItem
	| Slug
	| CloudinaryAsset
	| Testimonial
	| Social
	| SiteProfile
	| SectionHeader
	| Project
	| Experience
	| Company
	| CloudinaryAssetContextCustom
	| CloudinaryAssetContext
	| CloudinaryAssetDerived
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityImageHotspot
	| SanityImageCrop
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: testimonialsQuery
// Query: *[_type == "testimonial"] | order(order asc) {    _id,    quote,    authorName,    authorRole,    authorAvatar,    company->{      _id,      name,      logo    }  }
export type TestimonialsQueryResult = Array<{
	_id: string;
	quote: string | null;
	authorName: string | null;
	authorRole: string | null;
	authorAvatar: CloudinaryAsset | null;
	company: {
		_id: string;
		name: string | null;
		logo: CloudinaryAsset | null;
	} | null;
}>;
// Variable: companiesQuery
// Query: *[_type == "company"] | order(order asc) {    _id,    name,		logo,		website,		description	}
export type CompaniesQueryResult = Array<{
	_id: string;
	name: string | null;
	logo: CloudinaryAsset | null;
	website: string | null;
	description: string | null;
}>;
// Variable: socialsQuery
// Query: *[_type == "social"] | order(order asc) {    _id,    label,    href,    icon  }
export type SocialsQueryResult = Array<{
	_id: string;
	label: string | null;
	href: string | null;
	icon: CloudinaryAsset | null;
}>;
// Variable: projectsQuery
// Query: *[_type == "project"] | order(order asc) {    _id,    name,    image,    alt,    backgroundColor  }
export type ProjectsQueryResult = Array<{
	_id: string;
	name: string | null;
	image: CloudinaryAsset | null;
	alt: string | null;
	backgroundColor: string | null;
}>;
// Variable: experiencesQuery
// Query: *[_type == "experience"] | order(order asc) {    _id,    company,    url,    role,    description  }
export type ExperiencesQueryResult = Array<{
	_id: string;
	company: string | null;
	url: string | null;
	role: string | null;
	description: string | null;
}>;
// Variable: siteProfileQuery
// Query: *[_type == "siteProfile"][0] {    _id,    name,    title,    bio  }
export type SiteProfileQueryResult = {
	_id: string;
	name: string | null;
	title: string | null;
	bio: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: "span";
			_key: string;
		}>;
		style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
		listItem?: "bullet" | "number";
		markDefs?: Array<{
			href?: string;
			_type: "link";
			_key: string;
		}>;
		level?: number;
		_type: "block";
		_key: string;
	}> | null;
} | null;
// Variable: workPageQuery
// Query: *[_type == "company" && count(*[_type == "workItem" && references(^._id)]) > 0] | order(order asc) {    _id,    name,    logo,    website,    isCurrent,    workTagline,    workDescription,    "workItems": *[_type == "workItem" && references(^._id)] | order(order asc) {      _id,      title,      icon,      tag,      image,      description,      "slug": slug.current    }  }
export type WorkPageQueryResult = Array<{
	_id: string;
	name: string | null;
	logo: CloudinaryAsset | null;
	website: string | null;
	isCurrent: boolean | null;
	workTagline: string | null;
	workDescription: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: "span";
			_key: string;
		}>;
		style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
		listItem?: "bullet" | "number";
		markDefs?: Array<{
			href?: string;
			_type: "link";
			_key: string;
		}>;
		level?: number;
		_type: "block";
		_key: string;
	}> | null;
	workItems: Array<{
		_id: string;
		title: string | null;
		icon: CloudinaryAsset | null;
		tag: string | null;
		image: CloudinaryAsset | null;
		description: string | null;
		slug: string | null;
	}>;
}>;
// Variable: sectionHeaderQuery
// Query: *[_type == "sectionHeader" && slug.current == $slug][0] {    _id,    headingPrefix,    headingHighlight,    headingEmoji,    icon,    gradientFrom,    gradientTo,    video,    subheading  }
export type SectionHeaderQueryResult = {
	_id: string;
	headingPrefix: string | null;
	headingHighlight: string | null;
	headingEmoji: string | null;
	icon: CloudinaryAsset | null;
	gradientFrom: string | null;
	gradientTo: string | null;
	video: CloudinaryAsset | null;
	subheading: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
	interface SanityQueries {
		'\n  *[_type == "testimonial"] | order(order asc) {\n    _id,\n    quote,\n    authorName,\n    authorRole,\n    authorAvatar,\n    company->{\n      _id,\n      name,\n      logo\n    }\n  }\n': TestimonialsQueryResult;
		'\n  *[_type == "company"] | order(order asc) {\n    _id,\n    name,\n\t\tlogo,\n\t\twebsite,\n\t\tdescription\n\t}\n': CompaniesQueryResult;
		'\n  *[_type == "social"] | order(order asc) {\n    _id,\n    label,\n    href,\n    icon\n  }\n': SocialsQueryResult;
		'\n  *[_type == "project"] | order(order asc) {\n    _id,\n    name,\n    image,\n    alt,\n    backgroundColor\n  }\n': ProjectsQueryResult;
		'\n  *[_type == "experience"] | order(order asc) {\n    _id,\n    company,\n    url,\n    role,\n    description\n  }\n': ExperiencesQueryResult;
		'\n  *[_type == "siteProfile"][0] {\n    _id,\n    name,\n    title,\n    bio\n  }\n': SiteProfileQueryResult;
		'\n  *[_type == "company" && count(*[_type == "workItem" && references(^._id)]) > 0] | order(order asc) {\n    _id,\n    name,\n    logo,\n    website,\n    isCurrent,\n    workTagline,\n    workDescription,\n    "workItems": *[_type == "workItem" && references(^._id)] | order(order asc) {\n      _id,\n      title,\n      icon,\n      tag,\n      image,\n      description,\n      "slug": slug.current\n    }\n  }\n': WorkPageQueryResult;
		'\n  *[_type == "sectionHeader" && slug.current == $slug][0] {\n    _id,\n    headingPrefix,\n    headingHighlight,\n    headingEmoji,\n    icon,\n    gradientFrom,\n    gradientTo,\n    video,\n    subheading\n  }\n': SectionHeaderQueryResult;
	}
}
