import type { PortableTextBlock } from "next-sanity";
import "server-only";
import { tagResource } from "@/lib/caching";
import { getMediaUrl } from "@/lib/media";
import type {
	AllWorkItemSlugsQueryResult,
	CompaniesQueryResult,
	ExperiencesQueryResult,
	ProjectsQueryResult,
	SectionHeaderQueryResult,
	SiteProfileQueryResult,
	SocialsQueryResult,
	TestimonialsQueryResult,
	WorkItemBySlugQueryResult,
	WorkPageQueryResult,
} from "~/sanity.types";
import { sanityFetch } from "./fetch";
import {
	allWorkItemSlugsQuery,
	companiesQuery,
	experiencesQuery,
	projectsQuery,
	sectionHeaderQuery,
	siteProfileQuery,
	socialsQuery,
	testimonialsQuery,
	workItemBySlugQuery,
	workPageQuery,
} from "./queries";

/**
 * ========================
 * Sanity query result aliases
 *
 * Raw shapes come straight from `sanity.types.ts` (generated by
 * `bun run sanity:typegen`). Never hand-edit the generated file — any
 * schema change should be followed by a typegen run so these aliases stay
 * in sync with Studio.
 * ========================
 */

type TestimonialRaw = TestimonialsQueryResult[number];
type CompanyRaw = CompaniesQueryResult[number];
type SocialRaw = SocialsQueryResult[number];
type ProjectRaw = ProjectsQueryResult[number];
type ExperienceRaw = ExperiencesQueryResult[number];
type SectionHeaderRaw = NonNullable<SectionHeaderQueryResult>;
type WorkPageCompanyRaw = WorkPageQueryResult[number];
type WorkItemCardRaw = WorkPageCompanyRaw["workItems"][number];
type WorkItemDetailRaw = NonNullable<WorkItemBySlugQueryResult>;
type ContentBlockRaw = NonNullable<WorkItemDetailRaw["content"]>[number];
type ContentBlockOfType<T extends string> = Extract<
	ContentBlockRaw,
	{ _type: T }
>;

/**
 * ========================
 * Data transfer objects
 *
 * DTOs are what components consume. Everything here is trimmed of Sanity
 * internals (_ref, _type on references, internalGroqTypeReferenceTo) and has
 * required fields defaulted to sensible empty values so renderers don't have
 * to null-check every field.
 * ========================
 */

export interface CompanyDTO {
	name: string;
	logo: string;
	website?: string;
}

export interface TestimonialDTO {
	quote: PortableTextBlock[];
	authorName: string;
	authorRole: string;
	authorAvatar: string;
	company: CompanyDTO;
}

export interface SocialDTO {
	label: string;
	href: string;
	icon: string;
}

export interface ProjectDTO {
	name: string;
	image: string;
	alt: string;
	backgroundColor: string;
}

export interface ExperienceDTO {
	company: string;
	url: string;
	role: string;
	description: string;
}

export interface SiteProfileDTO {
	name: string;
	title: string;
	bio: PortableTextBlock[];
}

export interface WorkItemDTO {
	title: string;
	icon?: string;
	tag: string;
	image: string;
	description: string;
	slug: string;
	brandFrom?: string;
	brandTo?: string;
}

export interface TeamMemberDTO {
	name: string;
	role: string;
	avatar?: string;
}

export interface BrandDTO {
	primary?: string;
	secondary?: string;
	accent?: string;
	muted?: string;
}

export interface ContentImageDTO {
	_type: "contentImage";
	_key: string;
	url: string;
	alt: string;
	caption?: string;
	size: "inline" | "wide" | "full";
}

export interface ContentTestimonialDTO {
	_type: "contentTestimonial";
	_key: string;
	testimonial: TestimonialDTO;
}

export interface ContentDividerDTO {
	_type: "contentDivider";
	_key: string;
	style: "line" | "space";
}

export interface ContentVideoDTO {
	_type: "contentVideo";
	_key: string;
	url: string;
	caption?: string;
	autoplay: boolean;
	loop: boolean;
	muted: boolean;
	controls: boolean;
}

export interface ContentMetaDTO {
	_type: "contentMeta";
	_key: string;
	role?: string;
	team: TeamMemberDTO[];
	timeline?: string;
	tools: string[];
}

export type ContentBlock =
	| PortableTextBlock
	| ContentImageDTO
	| ContentTestimonialDTO
	| ContentDividerDTO
	| ContentVideoDTO
	| ContentMetaDTO;

export interface WorkNavLinkDTO {
	title: string;
	slug: string;
	tag: string;
}

export interface WorkItemDetailDTO {
	title: string;
	slug: string;
	tag: string;
	description: string;
	excerpt?: PortableTextBlock[];
	brand: BrandDTO;
	liveUrl?: string;
	heroImage: string;
	content: ContentBlock[];
	prev: WorkNavLinkDTO | null;
	next: WorkNavLinkDTO | null;
	company: CompanyDTO;
}

export interface WorkPageCompanyDTO {
	name: string;
	logo: string;
	website?: string;
	isCurrent: boolean;
	badge?: string;
	workTagline?: string;
	workDescription?: PortableTextBlock[];
	workItems: WorkItemDTO[];
}

export interface SectionHeaderDTO {
	headingPrefix?: string;
	headingHighlight: string;
	headingEmoji?: string;
	icon?: string;
	gradientFrom?: string;
	gradientTo?: string;
	videoUrl?: string;
	subheading?: string;
}

/**
 * ========================
 * Transformers (raw → DTO)
 *
 * All transformers accept the generated raw shape and return a DTO. Every
 * default here documents what "empty" looks like downstream.
 * ========================
 */

function toCompanyDTO(data: CompanyRaw): CompanyDTO {
	return {
		name: data.name ?? "",
		logo: getMediaUrl(data.logo),
		website: data.website ?? undefined,
	};
}

function toTestimonialDTO(data: TestimonialRaw): TestimonialDTO {
	return {
		quote: (data.quote ?? []) as PortableTextBlock[],
		authorName: data.authorName ?? "",
		authorRole: data.authorRole ?? "",
		authorAvatar: getMediaUrl(data.authorAvatar),
		company: {
			name: data.company?.name ?? "",
			logo: getMediaUrl(data.company?.logo),
		},
	};
}

function toSocialDTO(data: SocialRaw): SocialDTO {
	return {
		label: data.label ?? "",
		href: data.href ?? "",
		icon: getMediaUrl(data.icon),
	};
}

function toProjectDTO(data: ProjectRaw): ProjectDTO {
	return {
		name: data.name ?? "",
		image: getMediaUrl(data.image),
		alt: data.alt ?? "",
		backgroundColor: data.backgroundColor ?? "",
	};
}

function toExperienceDTO(data: ExperienceRaw): ExperienceDTO {
	return {
		company: data.company ?? "",
		url: data.url ?? "",
		role: data.role ?? "",
		description: data.description ?? "",
	};
}

function toWorkItemCardDTO(data: WorkItemCardRaw): WorkItemDTO {
	return {
		title: data.title ?? "",
		icon: data.icon ? getMediaUrl(data.icon) : undefined,
		tag: data.tag ?? "",
		image: getMediaUrl(data.image),
		description: data.description ?? "",
		slug: data.slug ?? "",
		brandFrom: data.brandFrom ?? undefined,
		brandTo: data.brandTo ?? undefined,
	};
}

function toWorkPageCompanyDTO(data: WorkPageCompanyRaw): WorkPageCompanyDTO {
	return {
		name: data.name ?? "",
		logo: getMediaUrl(data.logo),
		website: data.website ?? undefined,
		isCurrent: data.isCurrent ?? false,
		badge: data.badge ?? undefined,
		workTagline: data.workTagline ?? undefined,
		workDescription: (data.workDescription ?? undefined) as
			| PortableTextBlock[]
			| undefined,
		workItems: (data.workItems ?? []).map(toWorkItemCardDTO),
	};
}

function toSectionHeaderDTO(data: SectionHeaderRaw): SectionHeaderDTO {
	return {
		headingPrefix: data.headingPrefix ?? undefined,
		headingHighlight: data.headingHighlight ?? "",
		headingEmoji: data.headingEmoji ?? undefined,
		icon: data.icon ? getMediaUrl(data.icon) : undefined,
		gradientFrom: data.gradientFrom ?? undefined,
		gradientTo: data.gradientTo ?? undefined,
		videoUrl: data.video ? getMediaUrl(data.video) : undefined,
		subheading: data.subheading ?? undefined,
	};
}

// ----- Content block transformers -----

function toContentImageDTO(
	data: ContentBlockOfType<"contentImage">,
): ContentImageDTO {
	return {
		_type: "contentImage",
		_key: data._key,
		url: getMediaUrl(data.asset),
		alt: data.alt ?? "",
		caption: data.caption ?? undefined,
		size: data.size ?? "inline",
	};
}

function toContentTestimonialDTO(
	data: ContentBlockOfType<"contentTestimonial">,
): ContentTestimonialDTO | null {
	if (!data.testimonial) return null;
	return {
		_type: "contentTestimonial",
		_key: data._key,
		testimonial: toTestimonialDTO(data.testimonial),
	};
}

function toContentDividerDTO(
	data: ContentBlockOfType<"contentDivider">,
): ContentDividerDTO {
	return {
		_type: "contentDivider",
		_key: data._key,
		style: data.style ?? "line",
	};
}

function toContentVideoDTO(
	data: ContentBlockOfType<"contentVideo">,
): ContentVideoDTO | null {
	const url = getMediaUrl(data.asset);
	if (!url) return null;
	return {
		_type: "contentVideo",
		_key: data._key,
		url,
		caption: data.caption ?? undefined,
		autoplay: data.autoplay ?? false,
		loop: data.loop ?? false,
		muted: data.muted ?? true,
		controls: data.controls ?? true,
	};
}

function toContentMetaDTO(
	data: ContentBlockOfType<"contentMeta">,
): ContentMetaDTO {
	const team = (data.team ?? [])
		.map<TeamMemberDTO>((m) => ({
			name: m.name ?? "",
			role: m.role ?? "",
			avatar: m.avatar ? getMediaUrl(m.avatar) || undefined : undefined,
		}))
		.filter((m) => m.name.length > 0);

	return {
		_type: "contentMeta",
		_key: data._key,
		role: data.role ?? undefined,
		team,
		timeline: data.timeline ?? undefined,
		tools: data.tools ?? [],
	};
}

function hasType<T extends string>(
	block: ContentBlockRaw,
	type: T,
): block is ContentBlockOfType<T> {
	return block._type === type;
}

function toContentBlock(block: ContentBlockRaw): ContentBlock | null {
	if (hasType(block, "contentImage")) return toContentImageDTO(block);
	if (hasType(block, "contentTestimonial"))
		return toContentTestimonialDTO(block);
	if (hasType(block, "contentDivider")) return toContentDividerDTO(block);
	if (hasType(block, "contentVideo")) return toContentVideoDTO(block);
	if (hasType(block, "contentMeta")) return toContentMetaDTO(block);
	// Pass-through for PortableText `block` — the generated shape is a superset
	// of `PortableTextBlock` so the cast is safe at runtime.
	return block as unknown as PortableTextBlock;
}

function toWorkNavLink(
	raw: NonNullable<WorkItemDetailRaw["prev"]>,
): WorkNavLinkDTO | null {
	if (!raw.slug) return null;
	return {
		title: raw.title ?? "",
		slug: raw.slug,
		tag: raw.tag ?? "",
	};
}

function toWorkItemDetailDTO(data: WorkItemDetailRaw): WorkItemDetailDTO {
	const heroImage = getMediaUrl(data.heroImage) || getMediaUrl(data.image);
	const content = (data.content ?? [])
		.map(toContentBlock)
		.filter((b): b is ContentBlock => b !== null);

	return {
		title: data.title ?? "",
		slug: data.slug ?? "",
		tag: data.tag ?? "",
		description: data.description ?? "",
		excerpt: (data.excerpt ?? undefined) as PortableTextBlock[] | undefined,
		brand: {
			primary: data.brand?.primary ?? undefined,
			secondary: data.brand?.secondary ?? undefined,
			accent: data.brand?.accent ?? undefined,
			muted: data.brand?.muted ?? undefined,
		},
		liveUrl: data.liveUrl ?? undefined,
		heroImage,
		content,
		prev: data.prev ? toWorkNavLink(data.prev) : null,
		next: data.next ? toWorkNavLink(data.next) : null,
		company: {
			name: data.company?.name ?? "",
			logo: getMediaUrl(data.company?.logo),
			website: data.company?.website ?? undefined,
		},
	};
}

/**
 * ========================
 * Cached Data Getters
 * ========================
 */

export async function getTestimonials(): Promise<TestimonialDTO[]> {
	await tagResource("testimonial");

	const testimonials = await sanityFetch<TestimonialsQueryResult>({
		query: testimonialsQuery,
	});
	return testimonials.map(toTestimonialDTO);
}

export async function getCompanies(): Promise<CompanyDTO[]> {
	await tagResource("company");

	const companies = await sanityFetch<CompaniesQueryResult>({
		query: companiesQuery,
	});
	return companies.map(toCompanyDTO);
}

export async function getSocials(): Promise<SocialDTO[]> {
	await tagResource("social");

	const socials = await sanityFetch<SocialsQueryResult>({
		query: socialsQuery,
	});
	return socials.map(toSocialDTO);
}

export async function getProjects(): Promise<ProjectDTO[]> {
	await tagResource("project");

	const projects = await sanityFetch<ProjectsQueryResult>({
		query: projectsQuery,
	});
	return projects.map(toProjectDTO);
}

export async function getExperiences(): Promise<ExperienceDTO[]> {
	await tagResource("experience");

	const experiences = await sanityFetch<ExperiencesQueryResult>({
		query: experiencesQuery,
	});
	return experiences.map(toExperienceDTO);
}

export async function getSiteProfile(): Promise<SiteProfileDTO | null> {
	await tagResource("siteProfile");

	const profile = await sanityFetch<SiteProfileQueryResult>({
		query: siteProfileQuery,
	});
	if (!profile) return null;
	return {
		name: profile.name ?? "",
		title: profile.title ?? "",
		bio: (profile.bio ?? []) as unknown as PortableTextBlock[],
	};
}

export async function getSectionHeader(
	slug: string,
): Promise<SectionHeaderDTO | null> {
	await tagResource("sectionHeader");

	const header = await sanityFetch<SectionHeaderQueryResult>({
		query: sectionHeaderQuery,
		params: { slug },
	});
	if (!header) return null;
	return toSectionHeaderDTO(header);
}

export async function getWorkPageCompanies(): Promise<WorkPageCompanyDTO[]> {
	await tagResource("workItem");
	await tagResource("company");

	const companies = await sanityFetch<WorkPageQueryResult>({
		query: workPageQuery,
	});
	return companies.map(toWorkPageCompanyDTO);
}

export async function getWorkItemBySlug(
	slug: string,
): Promise<WorkItemDetailDTO | null> {
	// Tag all three — the detail page embeds testimonial references inline, so
	// edits to an embedded testimonial doc should bust this page's cache.
	await tagResource("workItem");
	await tagResource("company");
	await tagResource("testimonial");

	const data = await sanityFetch<WorkItemBySlugQueryResult>({
		query: workItemBySlugQuery,
		params: { slug },
	});
	if (!data) return null;
	return toWorkItemDetailDTO(data);
}

export async function getAllWorkItemSlugs(): Promise<string[]> {
	await tagResource("workItem");

	const slugs = await sanityFetch<AllWorkItemSlugsQueryResult>({
		query: allWorkItemSlugsQuery,
	});
	return slugs.filter((s): s is string => s !== null);
}
